language: java
jdk:
- oraclejdk8
env:
  global:
  - ACTIVATOR_VERSION=1.3.7
  - ACTIVATOR_ZIP_FILE=typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
  - ACTIVATOR_ZIP_URL=http://downloads.typesafe.com/typesafe-activator/${ACTIVATOR_VERSION}/${ACTIVATOR_ZIP_FILE}
  - PLAY2_HOME=${TRAVIS_BUILD_DIR}/activator-${ACTIVATOR_VERSION}-minimal
  - SBT_EXECUTABLE_NAME=activator
  - GH_REF=github.com/theAgileFactory/maf-dbmdl
  - secure: TatTcbF+zDEd5A48hxh94BLQGgzY8D8E/dgqS5AVaRgpFj5tlwl+aD+9FRKWBYe6qylItY4qdSysa32YWnO5p2GOI1ZNuqELyLZ/oD8yvfeEAnmXobU8/o9buOR7pSprLQDt1XFWtmnfBB98ofILB4iaRYCphGHA+ejazXzRyErMLwRewVoZ3gR9DwLpoLHA6st2rZK8TGjuid0kJEYKSL88JyhQnwQUNkdy60jyWpsB4Av5poK74Kd1WVdYoJrR5OxeNWFz6n/69ItdW9vYTpxFy5xa3Plr/wfM84uR2pKAWKb329bf4VUmNfwT9hH9+dB8CLKr8v08EOnTGAGNvcxFocNf13DUf4w6QATaU0lT3NuCf0WygE30yKVcqNJw2DHLrMksBcW77pXoNckB1bejG0/gJkyvglpLQF7vwo1Rzp4TulzMhNl5XLbBvOT6pvpGRwnFy7kQFUQHOqbFfhhseHxKM1O2Kg2m81w9daPjy3sjt0wogi5S2A5F6MONGDEEMKG8ia+WcbDsoXHZ4CqXrfuO2gEqhgVtmD8+m3ovT1hrWDptOqVL4DJpsFLFjt4b1MbQoScDUpPGQH0WJgAuL+u4JUGV6l6URQvdHKGt+aDzhHTZE6+RyBukLAAmAbkLHl//qq37wAb114N4QhLmUPL/XbXwU5V6Dn6zNTo=
  - secure: OAYaHF8lU8qxh8BQxP4FoUCOsKLP4iyhV+M2PVLrLUP9XDjTpEpHighji6Q5JL3cgVm+tQtvy5S/IbJWZFQggH3wSeHH2PrwtjHLgEWagkBPzBXVJMqeDl+1jdGlBZVqNrYwsa5QwUYVEWtyDpbSu8c39tiIg1zIYybz0fYB6AsNuNs5pIZC3PdPXgRcMrt/vu21YsFpLERkoM4pwBv/wLf1gmwZeKyjIHNGyXlxkUtBCMEnzAnfXAfBAmwlmBvuOVPKzwrIthW5d+E/gji+Wh9W6odDu18FbSiEpS1N4GumtJfj5rI2fTLD+AzmF/sYNKnFpY8CltnIWnBUqGotG6Y/+fjSDdhhKfLdD8MQgPtKrN+VuSgns8zzgNymopIry5VUFZ/f7qU/Yiy4vJ/bi3OpYtlyS6tm8iGbzv2fG6cTxlLllo0yYqX8F9JOPqlUz2IMC8R0XIHj9xtMxiq6E41giLzsjvYj9Pc8g9rDFIl7vub7We3D3Gri+Zht/p4gspMq3fkzYAxXBU7upN/3ewEAMd2kxXKeDtP4fu3DRljd/PQ1qMQrAWQPBzVAqufUAI9bOR2q6Qpr+ZWWRpZ1N3cHV/kMU0WJN/Ev5UKfuyvDgaTrHO1J6gcCbzQ0jAvdOJP0+oPJY5vktpUPP4jHnOr4LaIy+aDAFM+5iY02/is=
  - secure: HNdP3BuxBxDOiVVsJq1enaQXYb/+5cCncth6LFxX8r9o3rNMtU156jd6OyQcS4w07BFyVyAmPFqVwOABNZXISPc9bmZTtuUZLC8NiSkouHAgr3no0UHQEt7HEt0KZdi5aHkDGzSVOOrSSxzffdjibQbdAq0TKQKoEmWPjRrDIiP156LURkcfxJ/OPPzNx+PjvbtTnCWxFnLlsQ3od8es5U+aPd4VA1JUI/mRJ/2CV9yfIQeyfjdXqf7FpBK0tXhjH+VVidSq0cxwPjg2jKFuyWPu/wJ0bo9JbMjf8FGY72eTDthzmPANR+nFxuHmUlvNpUzxFGV0rO5Oaip96y7NOytfhqg7idHr43XOp5p9iHJ7900gSQZpMn9noNfzaLuWAOPQFVJ7yYL/WRVG7G9Wel7kpBU1+TJRVqgqX1ZRZA3flHCcxchDCeiAvfnunS/f+biu93bMncM6JFbY5DWAoQeX7ZxaOZbCvSc8mneJRQ+7coGGk77PD5OP5nd/+0hafalEqBdAvpyy5gebgPCniFCxDUA84/lFskMT9mQLWwrZ0AlRR2R9uutphR39hMR330SIJsx+41ziZfepHtMLgL3zdRq6CHUjac+IyarvywEk0KbQYqHwITJbH1kFVprNu3edieZGii9fOlSG0/+8rB/wrgCaD1J6jZ/JGaNMXro=
  - secure: qV4K7LDA0MXuTPIVKp7VbLHp34H3fasKx+ONEeqzhes42DwfZ4FxUjNdokhbG/Jcdg4FXZkIvIYaYSEsDZxOw4tjIyTeP4pOyXT6hxh+dberWpDCZH9g6F6LMso4SfGsyBMV6u5HLnzObFUedeWs0S+odyxMpro/Op0Q7TxqjmcEMD0UyoMlNZAkIMkvE3T2/z7NTtH0/xAEA2yTwUYNXSzjXsHjFJxbOxXt7fEgusdKCBNI6UsKZ1ajbK2KGBNvGf7VfuHCd7ApEUCKwmnPLEr6XYM3Vw7CTtWfFDsGBKZty0DNEzb5IcQdp/bLoVq9O9/MML2ckGNwWtYOHvMWjnGCCtCqjhJUPvaLsXiSYop+nVneF04NBruJoIIvp/r8ENLQK/0xDGOfEY4l6jXz4Zv1us0fVej506qkxr9GtVMXXR5IqjyfUph2dKW+XmGRU4yFbT4IcnidbyOSjTI+GTnaE+9oSpSytd1EzQIUvqqCV0MvWJy/fkLMnEIbY9wo68VVv9Lr8P1skBwpT35SlJoHGpc4MseHppUWrNlYGBB48459FLFgjXZAsqMgGAbM3rCFqpReD3guAUnhEIgUGwx6xWwmK2WiekF65NphUaeJXZqBvKGtnhD/RppzrcORqWkpW49psv6JfT6KnvwHloTTkpmQ2m5aora/Cs1ZWCc=
before_install:
- sudo apt-get update
- sudo apt-get install --only-upgrade -y oracle-java8-installer
- mkdir -p ~/.gnupg
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in secring.gpg.enc -out ~/.gnupg/secring.gpg
  -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in pubring.gpg.enc -out ~/.gnupg/pubring.gpg
  -d
- echo "<settings><servers><server><id>ossrh</id><username>\${OSSRH_JIRA_USERNAME}</username><password>\${OSSRH_JIRA_PASSWORD}</password></server></servers></settings>"
  > ~/.m2/settings.xml
install:
- wget ${ACTIVATOR_ZIP_URL}
- unzip -q ${ACTIVATOR_ZIP_FILE}
script:
- mvn clean install -Dgpg.passphrase="${GPG_PASSPHRASE}" --settings ~/.m2/settings.xml
after_success:
- .travis/deploy.sh
after_script:
- rm ~/.gnupg/secring.gpg
- rm ~/.gnupg/pubring.gpg
- rm ~/.m2/settings.xml
notifications:
  email: true
branches:
  only:
  - master
  - R16
scala:
- 2.11.8
cache:
  directories:
  - .autoconf
  - ~/.m2
  - ~/.sbt
  - ~/.ivy
